receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:

exporters:
  otlphttp/nginx:
    endpoint: http://otel-proxy:4319/ingest/hostmetrics-tenant

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [otlphttp/nginx]
